name: "dwgf"
deg: "inp_large_box"
sigma_x0: 0.001
denoise_term_weight: "linear" #"linear", "sqrt", "log", "square", "trunc_linear", "const", "power2over3"

n_particles: 4
w_t: 0.15
lr_z: 1.0 # latent lr
vjp_coeff: 0.1
decoder_std: 0.01 # noise std for decoder